name: Pull Docker Image-1

on:
  push:
    branches:
      - main

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Pull Docker Image
      run: |
        docker pull ubuntu:latest

    - name: Display Docker Image
      run: |
        docker images
